Fix setup.sh issue + add basic test

diff --git a/buildenv b/buildenv
--- a/buildenv
+++ b/buildenv
@@ -1,9 +1,13 @@
-export ZOPEN_TARBALL_URL="https://invisible-mirror.net/archives/lynx/tarballs/lynx2.8.9rel.1.tar.gz"
+VERSION="2.8.9"
+export ZOPEN_TARBALL_URL="https://invisible-mirror.net/archives/lynx/tarballs/lynx${VERSION}rel.1.tar.gz"
 export ZOPEN_TARBALL_DEPS="make ncurses zoslib openssl"
 export ZOPEN_TYPE="TARBALL"
-export ZOPEN_EXTRA_CFLAGS="-I\$ZOSLIB_HOME/include -I\$NCURSES_HOME/include/ncurses -I${ZOPEN_ROOT}/lynx2.8.9rel.1"
+export ZOPEN_EXTRA_CFLAGS="-I\$ZOSLIB_HOME/include -I\$NCURSES_HOME/include/ncurses -I${ZOPEN_ROOT}/lynx${VERSION}rel.1"
 export ZOPEN_MAKE_OPTS="-j$NUM_JOBS"
+export ZOPEN_NAME="lynx-${VERSION}"
 export ZOPEN_MAKE_MINIMAL="yes"
+export ZOPEN_CHECK="./lynx"
+export ZOPEN_CHECK_OPTS="--version"
 
 export ZOPEN_EXTRA_CONFIGURE_OPTS="--with-ssl=yes --without-pkg-config"
 
@@ -13,8 +17,9 @@ zopen_check_results()
   pfx="$2"
   chk="$1/$2_check.log"
 
-  # Echo the following information to gauge build health
-  echo "actualFailures:0"
+  grep -q "${VERSION}" $chk
+  failures=$?
+  echo "actualFailures:$failures"
   echo "totalTests:1"
   echo "expectedFailures:0"
 }
